"""iCloud Mail event source and deterministic routing."""

from .models import (
    BackfillSummary,
    Importance,
    MailMetadata,
    MailRoute,
    MailRoutes,
    RestoreSummary,
    RouteLintReport,
    RouteOverlap,
    RuleLint,
    SuggestedAction,
)
from .reader import MailReader
from .runtime import (
    FULL_QUERY,
    HEADER_QUERY,
    IMAP_HOST,
    MailLoop,
    MailProcessor,
    MailState,
    backfill_inbox,
    build_mail_turn_prompt,
    cheap_triage,
    ensure_folders,
    lint_mail_routes,
    load_routes,
    move_messages,
    parse_metadata,
    record_current_mail_decision,
    render_message,
    restore_folder_to_inbox,
)

__all__ = [
    "FULL_QUERY",
    "HEADER_QUERY",
    "IMAP_HOST",
    "BackfillSummary",
    "Importance",
    "MailLoop",
    "MailMetadata",
    "MailProcessor",
    "MailRoute",
    "MailRoutes",
    "MailReader",
    "MailState",
    "RestoreSummary",
    "RouteLintReport",
    "RouteOverlap",
    "RuleLint",
    "SuggestedAction",
    "backfill_inbox",
    "build_mail_turn_prompt",
    "cheap_triage",
    "ensure_folders",
    "load_routes",
    "lint_mail_routes",
    "move_messages",
    "parse_metadata",
    "record_current_mail_decision",
    "render_message",
    "restore_folder_to_inbox",
]
